### ISSUE TITLE
Authorization fix

### ISSUE THREAD

**Issue by karimovnurullo** [SardorOchilov/book-search#1]
When entering the Site, the user must first log in and then go to the main page. Do not go to the main page without logging in

**Comment by SardorOchilov** [comment]
Ok I just fixed this problem. When user enter the site he will see all books but can not enter to single book page whithout registering or login. Iappreciated your attantion.

**Comment by SardorOchilov** [comment]
fixed

**Comment by SardorOchilov** [comment]
fixed
