### ISSUE TITLE
Unnecessary part of Authorization

### ISSUE THREAD

**Issue by ashomurodov** [SardorOchilov/book-search#2]
Login Va Register ikkalasi ham bitta vazifani bajaryabdi shunchaki Registrni o'zini qoldirib qo'ysangiz ham bo'ladi

**Comment by SardorOchilov** [comment]
E'tiboringiz uchun rahmat. Ularning vazifasi bir emas eid, lekin endi ularni yanada optimallashitirib togirlab qoydik, tekshirib korib yana kamchiliklari bolsa bizga murojat qilishingizni so'raymiz. Rahmat!

**Comment by ashomurodov** [comment]
))
