### ISSUE TITLE
Issiue of single book's categories

### ISSUE THREAD

**Issue by ashomurodov** [SardorOchilov/book-search#3]
Kitobning categoriya bo'limidagi kategorialar array ichida qolib ketibdi. Arrayni for bilan aylanib har bir kategoriya uchun bittadan list elementi chizib kategorialarni listga o'rab qo'ysangiz yaxshi bo'ladi

**Comment by SardorOchilov** [comment]
E'tiboringiz uchun rahmat bu muommoni to'g'irlab qoydik.

**Comment by ashomurodov** [comment]
🔥
